jwt:
  secretKey: sdfksdhfoiashdlknaknsvkasuifasdnckjasbgdpwrfnacsldkjvbuiapsdbf

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: inventory-service
              uri: lb://INVENTORY-SERVICE
              predicates:
                - Path=/api/v1/**
              filters:
                - StripPrefix=2
#                - name: LoggingOrder
                - name: Authentication
                  args:
                    isAuthenticationEnabled : true #passing the arguement to the config
                    isAuthorizationEnabled : true #passing the arguement to the config
#                - name: Authorization
#                  args:
#                    allowedRoles: ADMIN , SUPER_ADMIN

            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/v1/**
              filters:
                - StripPrefix=2
                - AddRequestHeader=x-custom-header,Nishant
                - name: Authentication
                  args:
                    isAuthenticationEnabled: true #passing the arguement to the config
                    isAuthorizationEnabled: true #passing the arguement to the config
#                - name: Authorization
#                  args:
#                    allowedRoles: ADMIN , SUPER_ADMIN
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka





# Remmeber this :  not - name: AuthenticationGatewayFilterFactory -> - name: Authentication
#      Spring Cloud Gateway does NOT use full class names.
#      It automatically strips:
#      GatewayFilterFactory
#      Filter
