spring:
  kafka:
    bootstrap-servers: localhost:9093

kafka:
  topic:
    user-random-topic: user-random-topic
    user-created-topic: user-created-topic

    producer:
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
        properties:
          schema.registry.url: http://localhost:8081
      acks: all
      retries: 3 #if a message is not consumed by the consumer then producer will product max 3 times

      properties:
        spring.json.add.type.headers: false   # optional but recommended
