spring:
  kafka:
    bootstrap-servers: localhost:9092

kafka:
  topic:
    user-random-topic: user-random-topic
    user-created-topic: user-created-topic

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring.json.add.type.headers: false   # optional but recommended
