#resilience4j:
#  circuitbreaker:
#    instances:
#      defaultCB:
#        registerHealthIndicator: true
#        slidingWindowSize: 20
#        slidingWindowType: COUNT_BASED
#        minimumNumberOfCalls: 10
#        failureRateThreshold: 50
#        waitDurationInOpenState: 10s
#        permittedNumberOfCallsInHalfOpenState: 5
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#
#  retry:
#    instances:
#      inventoryRetry:
#        maxAttempts: 3
#        waitDuration: 2s
#        enableExponentialBackoff: true
#        exponentialBackoffMultiplier: 2
#
#  ratelimiter:
#    instances:
#      defaultRateLimiter:
#        limitForPeriod: 10
#        limitRefreshPeriod: 1s
#        timeoutDuration: 0
#
#  bulkhead:
#    instances:
#      defaultBulkhead:
#        maxConcurrentCalls: 10
#        maxWaitDuration: 0
#
#  thread-pool-bulkhead:
#    instances:
#      defaultTPBulkhead:
#        maxThreadPoolSize: 10
#        coreThreadPoolSize: 5
#        queueCapacity: 20
